### PR TITLE
dhis2: fix dhis2 metadata

### LINKED ISSUE #1268: dhis2 7.0: metadata seems to be broken
Something changed

```
[CLI] ❯ Loading state...
[CLI] ✔ Loaded state from tmp/dhis2.json
[CLI] ❯ state: {
  "configuration": {
    "username": "****",
    "password": "****",
    "hostUrl": "****"
  }
}
[CLI] ✔ Generating metadata
[CLI] ℹ config: {
  "configuration": {
    "username": "****",
    "password": "****",
    "hostUrl": "****"
  }
}
[CLI] ❯ config hash:  1b4605e0ba3b6751196a11cbf80ad12aa7d072cddbb082d8e600e98448ce0b73
[CLI] ✔ Installing packages...
[CLI] ❯ repoDir is set to: /home/joe/repo/openfn/cli-repo
[CLI] ℹ Looked up latest version of @openfn/language-dhis2: found 7.0.2
[CLI] ℹ Skipping @openfn/language-dhis2@7.0.2 as already installed
[CLI] ✔ Installation complete in 296ms
[CLI] ❯ Using latest installed version of @openfn/language-dhis2: 7.0.2
[CLI] ❯ loading adaptor from /home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/dist/index.cjs
[CLI] ℹ Metadata function found. Generating metadata...
Using latest available version of the DHIS2 api on this server.
[CLI] ✘ Exception while generating metadata
[CLI] ✘ TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at dispatchHttpRequest (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:2805:20)
    at /home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:2725:5
    at new Promise (<anonymous>)
    at wrapAsync (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:2705:10)
    at http (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:2743:10)
    at Axios.dispatchRequest (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:4120:10)
    at Axios._request (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:4420:33)
    at Axios.request (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:4275:25)
    at wrap (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:31:15)
    at Axios.request (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/node_modules/axios/dist/node/axios.cjs:4280:41)
    at async Object.getOrgUnits (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/dist/index.cjs:219:22)
    at async Module.metadata (/home/joe/repo/openfn/cli-repo/node_modules/@openfn/language-dhis2_7.0.2/dist/index.cjs:254:17)
    at async metadataHandler (file:///home/joe/repo/openfn/kit/packages/cli/dist/process/runner.js:2085:22)
    at async parse (file:///home/joe/repo/openfn/kit/packages/cli/dist/process/runner.js:2431:12) {
  code: 'ERR_INVALID_URL',
  input: '/api/organisationUnits'
```

### PR DESCRIPTION
**Pull request by hunterachieng**
## Summary

Fix `dhis2` metadata `helper` and `config`

Fixes #1268 

## Details

Add technical details of what you've changed (and why).

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to
know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our
[Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Review Checklist

Before merging, the reviewer should check the following items:

- [ ] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, added the adaptor on marketing website ?
- [ ] If this PR includes breaking changes, do we need to update any jobs in
      production? Is it safe to release?
- [ ] Are there any unit tests?
- [ ] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.
- [ ] Have you ticked a box under AI Usage?

### CODE REVIEW

File: packages/dhis2/src/meta/config.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 // Config for dhis2 sandbox
 export default {
   configuration: {
-    hostUrl: 'https://play.im.dhis2.org/stable-2-42-1',
+    hostUrl: 'https://play.im.dhis2.org/dev-2-40',
```
Comment (josephjclark) [inline packages/dhis2/src/meta/config.js:4]: Shouldn't it just be `/dev`? The idea of this was that the URL would never have to change

See https://play.im.dhis2.org/dev/login/

Comment (hunterachieng) [reply packages/dhis2/src/meta/config.js]: Fixed
