### PR TITLE
inform: fix failing `http` export 

### LINKED ISSUE #1324: inform: `http` export not working
#### Description

The `inform` adaptor's `http` export throws this error:

```
SyntaxError: The requested module '@openfn/language-inform' does not provide an export named 'http'
R/T Run complete with status: crash

```

Image

Suggested fix: Ensure `http` namespace export works

### PR DESCRIPTION
**Pull request by hunterachieng**
## Summary

- Removed `common` exports in http

Fixes #1324 

## Details

- The installed `undici` was being used to import `fetch`. Deleting this automatically fixed the issue with the failing `http` export.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to
know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our
[Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Review Checklist

Before merging, the reviewer should check the following items:

- [x] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, added the adaptor on marketing website ?
- [ ] If this PR includes breaking changes, do we need to update any jobs in
      production? Is it safe to release?
- [ ] Are there any unit tests?
- [ ] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.
- [ ] Have you ticked a box under AI Usage?

### CODE REVIEW

**Comment by mtuchi** [comment]
@hunterachieng left you feedback on `changeset`, Please also look into failed tests in CI

**Comment by hunterachieng** [comment]
@mtuchi  I  have fixed it. I re-installed `undici` since we are using it in tests

File: packages/inform/src/Adaptor.js [hunk 1]
```diff
@@ -1,6 +1,5 @@
 import { expandReferences, encode } from '@openfn/language-common/util';
 import * as util from './Utils';
-import { fetch } from 'undici';
```
Comment (mtuchi) [inline packages/inform/src/Adaptor.js:3]: @hunterachieng looks like `fetch` is need in `downloadAttachment()` function. See https://github.com/OpenFn/adaptors/blob/main/packages/inform/src/Adaptor.js#L210

Comment (hunterachieng) [reply packages/inform/src/Adaptor.js:3]: @mtuchi  Yes. But to use fetch, I do not have to import from `undici` its redundant since it exists within node automatically. But `undici` is being used in tests.

Comment (josephjclark) [reply packages/inform/src/Adaptor.js:3]: Yep, `fetch()` is native so it's fine not use the undici import. You can probably remove the dev dependency from the package too.

Comment (josephjclark) [reply packages/inform/src/Adaptor.js:3]: Ah you're right - OK, fair enough!
